### ISSUE TITLE
The pre-trained model `KEEP-a1a14d46.pth` appears to be corrupted.

### ISSUE THREAD

**Issue by wrqcodedoge** [jnjaby/KEEP#7]
The pre-trained model `KEEP-a1a14d46.pth` appears to be corrupted.

**Comment by wrqcodedoge** [comment]
RuntimeError: unexpected EOF, expected 3565297 more bytes. The file might be corrupted.

**Comment by jnjaby** [comment]
Hi, you may try to manually download the pre-trained model from [Release](https://github.com/jnjaby/KEEP/releases/tag/v0.1.0).
